### ISSUE TITLE
Unable to parse character: _

### ISSUE THREAD

**Issue by StormsHalted** [NREL/glm#17]
- [ ] Python version: 3.11.1
- [ ] Python architecture:  [MSC v.1934 64 bit (AMD64)]
- [ ] Operating system and version: Windows 10 Enterprise
- [ ] glm version number: v0.4.3

I run a simple one line code using the glm package:

`import glm

l1 = glm.load("C:/3HT12F7clean.glm")`

I get this error:

![image](https://user-images.githubusercontent.com/105134867/230750577-d8caec4b-fb54-40df-a065-c0688bbf7a8a.png)

**Comment by kdheepak** [comment]
Can you try creating a smaller glm file that reproduce this error?

**Comment by StormsHalted** [comment]
Hi Dheepak, It is working with other smaller GLM file.

**Comment by kdheepak** [comment]
When there’s a Lexer error like this it means there’s a single character in the file that the parser (specifically the Lexer) in this package wasn’t expecting. Unfortunately just from the screenshot it is hard to say where or why that is. It seems like it’s from an `_` somewhere. 

If you tell me what block of code in the glm file is causing this issue, I might be able to narrow it down and fix it.

**Comment by kdheepak** [comment]
The quickest way to figure it out would be to do a binary partition. Delete half the file, run the python script, see if it errors. If it does, delete another half of the remaining and try again. If it doesn’t, delete the other original half of the file and try again, and repeat till you’ve been able to narrow it down.

**Comment by StormsHalted** [comment]
Okay,

I think I narrowed it down based on your direction: I make a new glm file with just one element copied from the big glm. Here is the simplified glm:

`object load 
{
	name "ld__8180106403";
	parent "_406-143197_N";
	phases ACN;
	nominal_voltage 120;
	constant_power_A 80.0+16.2447j;
	constant_power_C 80.0+16.2447j;
}`

As I change the parent attribute to `parent "406-143197_N";` It works. So apparently this underscore, which is present in many blocks (In original file) is the cause of issue.

**Comment by kdheepak** [comment]
Thanks for narrowing it down! I’ll look into this this weekend.

**Comment by kdheepak** [comment]
This particular issue is fixed for me now:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/1813121/230800047-fff01235-dd9f-4301-a9d7-22800f77980a.png">

I made a new release `v0.4.4` that should be on pypi shortly.

If something else breaks feel free to open a issue, and I'll look into it if I get the chance. If it is a low effort fix, I should be able to make a change fairly quickly.

Just as a FYI, this package is not actively maintained by me any more. I believe the current recommendation at NREL is to use https://github.com/NREL/ditto/ for parsing GridLAB-D or OpenDSS or any other distribution system data format. I'm no longer working at NREL so you might want to open an issue on that repo or email one of the current maintainers for more questions.

**Comment by StormsHalted** [comment]
Hi Dheepak, 

I did a `pip install --upgrade glm` but it says that:

`Requirement already satisfied: glm in c:\users\m.khan2\appdata\local\programs\spyder\python\lib\site-packages (0.4.3)
Note: you may need to restart the kernel to use updated packages.`

Appears that the upgrade hasn't reflected on pypi:

![image](https://user-images.githubusercontent.com/105134867/231040289-8007c21f-7a7a-4e8c-bf53-4fcd3d505fb5.png)

**Comment by StormsHalted** [comment]
@kdheepak  looks like it failed to publish on Pypi.

![image](https://user-images.githubusercontent.com/105134867/231243231-a9de80c0-1ae5-4066-9372-9242507ade3f.png)

**Comment by kdheepak** [comment]
Yeah, I noticed that the publish-pypi github action wasn't running yesterday and assumed it was just GitHub being slow. But I'm seeing the same thing again now:

<img width="650" alt="image" src="https://user-images.githubusercontent.com/1813121/231253044-95a16bb4-eba5-4ce7-aefc-2fb2199b43b3.png">

Usually this would start immediately but it's been over a minute in the screenshot over 3 minutes at the time I'm posting this comment and it hasn't started yet. I'm not sure what is going on here.

If it doesn't start soon, I think I'll have to fork and manually push to pypi.

**Comment by kdheepak** [comment]
I made a change to the github workflow and now it loads immediately. I believe it has been published now:

<img width="445" alt="image" src="https://user-images.githubusercontent.com/1813121/231256764-ddfd4bdf-1e0f-41b7-80fa-a8c32e9e1068.png">
