### ISSUE TITLE
Bug with editing old glm files

### ISSUE THREAD

**Issue by ibrahimkrad** [NREL/glm#4]
### Bug

Was updating the properties of inverters and had to make the following adjustments to get the new glm files to work:

1. Change the start time and end time for the clock objects to single quotes
2. Add the meter nested in the substation definition (this meter got lost in the rewrite)
3. Add the include commands in the beginning of the file
4. Add the player class definition for the delta loadshape

**Comment by kdheepak** [comment]
Thanks for opening the issue! I'll look into it.

**Comment by kdheepak** [comment]
> Add the meter nested in the substation definition (this meter got lost in the rewrite)

This will be fixed when #6 is merged.
